### ISSUE TITLE
When i called file recv func then my to_folder is returned null

### ISSUE THREAD

**Issue by paradey** [DTkalcec/portal#1]
Hi,

i debugged, myUI.Recv_ToFolder if i set my any folder here, return empty value and finding INBOX folder in same path with app.

![to1](https://user-images.githubusercontent.com/9864321/32535176-141c40ae-c46a-11e7-8169-4a7ed00a823a.png)

![to2](https://user-images.githubusercontent.com/9864321/32535177-1452582e-c46a-11e7-9dfc-3f39059dda96.png)

![to3](https://user-images.githubusercontent.com/9864321/32535178-1489dd4e-c46a-11e7-9f57-7732c6fc2299.png)

![to4](https://user-images.githubusercontent.com/9864321/32535778-9938ea42-c46c-11e7-8b51-116e3e8690c4.png)

![to_folder](https://user-images.githubusercontent.com/9864321/32535175-13e4cf7a-c46a-11e7-8bc5-8552dcda14e3.png)

**Comment by DTkalcec** [comment]
"UploadAnywhere" permission is required for a user to be allowed to upload files anywhere. If that permission was NOT granted to the user from whom files are being "fetched", then all files from that user will be stored in the default "INBOX" folder.
